### ISSUE TITLE
Docker daemon issue

### ISSUE THREAD

**Issue by serajhqi** [kha7iq/charts#1]
Hello

I deployed gitea act runner using your helm chart. I have the following step in my gitea actions:

```yaml
 - name: Set up Docker Buildx
   uses: docker/setup-buildx-action@v3
```

I get this error once it runs:

![image](https://github.com/kha7iq/charts/assets/7148972/80e1ff99-79b5-4855-aef1-dd508331c899)

How can I resolve it?

**Comment by kha7iq** [comment]
Hi @serajhqi  

This issue is not related to chart, i think you will be able to find a solution by either checking the act runner repo i.e https://gitea.com/gitea/act_runner/issues/280
Or 
docker/setup-buildx-action@v3 action

**Comment by serajhqi** [comment]
I had tried this solutions and I had no success. Actually I found it insecure to run it with root user on the server that my Kube was running. So Finally I managed to run it using docker compose on a separate server and connect it my Gitea. 

Thank you for your quick response and the this repo.

Best Regards

**Comment by kha7iq** [comment]
I am glad it worked out for you.
